[Variables]
Contribs=0

BackgroundColor=145,145,145,95
EmptyColor=235, 237, 240,95
Color1=155, 233, 168,200
Color2=64, 196, 99,200
Color3=48, 161, 78,200
Color4=33, 110, 57

TextColor=255,255,255,210
TextFont=Serif
TextSize=12
TextGap=20

Spacing=5
SquareSize=17
TextWidth=((#Spacing# * 2) + #SquareSize#)


[LogoStyle]
ImageName=#@#images/github_logo.png
ImageTint=235,235,235,155
H=28
W=28

[SquareStyle]
Padding=0,0,#Spacing#,#Spacing#
X=0r
Y=0R
H=#SquareSize#
W=#SquareSize#

[ActiveStyle]
H=#SquareSize#
W=#SquareSize#
FontFace=#TextFont#
FontSize=#TextSize#
FontColor=#TextColor#
AntiAlias=1


[LabelStyle]
FontSize=7
FontFace=#TextStyle#
FontColor=#TextColor#
X=3
Y=25r
H=#SquareSize#/2
W=#SquareSize#/2

[ConfigDesc]
FontFace=#TextFont#
FontSize=14
StringStyle=Bold
FontColor=230,230,230,240
StringEffect=Shadow
FontEffectColor = 0,0,0,200